name: Python Security Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety bandit
          pip install -r requirements.txt || true  # Ignore errors if file doesn't exist

      - name: Run Safety (Dependency Security Scan)
        run: safety check --full-report

      - name: Run Bandit (Security Linter)
        run: bandit -r . --exclude .venv,tests
